/*
 * 这里定义所有的action类型
 * */
//error
export const ERROR = 'ERROR';

//Account
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_VERIFICATION = 'GET_VERIFICATION';
export const GET_VERIFICATION_SUCCESS = 'GET_VERIFICATION_SUCCESS';
export const REGISTER = 'REGISTER';
export const RESET = 'RESET';
export const STOP_ACCOUNT_LOADING = 'STOP_ACCOUNT_LOADING';
export const SAVE_REGISTER_PARAMS = 'SAVE_REGISTER_PARAMS';
export const SET_VC_TIMER = 'SET_VC_TIMER';
export const ACCOUNT_END = 'ACCOUNT_END';

//Showcase
export const SHOWCASE_LIST_FETCH = 'SHOWCASE_LIST_FETCH';
export const SHOWCASE_LIST_FETCH_SUCCESS = 'SHOWCASE_LIST_FETCH_SUCEESS';
export const SHOWCASE_TEMPLATE_FETCH = 'SHOWCASE_TEMPLATE_FETCH';
export const SHOWCASE_TEMPLATE_FETCH_SUCCESS = 'SHOWCASE_TEMPLATE_FETCH_SSUCCESS';
export const TEMPLATE_FETCH = 'TEMPLATE_FETCH';
export const TEMPLATE_SUCCESS = 'TEMPLATE_SUCCESS';
export const RECOMMOND_FETCH = 'RECOMMOND_FETCH';
export const RECOMMOND_FETCH_SUCCESS = 'RECOMMOND_FETCH_SUCCESS';
export const PRODUCT_LIST_FETCH = 'PRODUCT_LIST_FETCH';
export const PRODUCT_LIST_FETCH_SUCCESS = 'PRODUCT_LIST_FETCH_SUCCESS';
export const SAVE_SHOWCASE_ID = 'SAVE_SHOWCASE_ID'
export const SHOWCASE_END = 'SHOWCASE_END';

//Product
export const PRODUCT_FETCH = 'PRODUCT_FETCH';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const RICHDETAIL_FETCH = 'RICHDETAIL_FETCH';
export const RICHDETAIL_FETCH_SUCCESS = 'RICHDETAIL_FETCH_SUCCESS';
export const FETCH_PRODUCT_INTREST = 'FETCH_PRODUCT_INTREST';
export const FETCH_PRODUCT_INTREST_SUCCESS = 'FETCH_PRODUCT_INTREST_SUCCESS';
export const SET_ACTIVEKEY = 'SET_ACTIVEKEY';
export const TOGGLE_PRODUCT_MODAL = 'TOGGLE_PRODUCT_MODAL';
export const INIT_PRODUCT = 'INIT_PRODUCT';
export const CHECKOUT_PRODUCT = 'CHECKOUT_PRODUCT';
export const PRODUCT_END = 'PRODUCT_END';

//Search
export const SEARCH_FETCH = 'SEARCH_FETCH';
export const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';
export const INIT_SEARCH = 'INIT_SEARCH';
export const SEARCH_END = 'SEARCH_END';

//Catelog
export const CATELOG_FETCH = 'CATELOG_FETCH';
export const CATELOG_FETCH_SUCCESS = 'CATELOG_FETCH_SUCCESS';
export const CATELOG_END = 'CATELOG_END';

//Life
export const FETCH_LIFE = 'FETCH_LIFE';
export const FETCH_LIFE_SUCCESS = 'FETCH_LIFE_SUCCESS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const LIFE_END = 'LIFE_END';
export const ADD_ID = 'ADD_ID';
export const SAVE_ID = 'SAVE_ID';

//Cart
export const QUERY_CART = 'QUERY_CART';
export const QUERY_CART_SUCCESS = 'QUERY_CART_SUCCESS';
export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const OPEN_CART_MODAL = 'OPEN_CART_MODAL';
export const OPEN_CART_MODAL_SUCCESS = 'OPEN_CART_MODAL_SUCCESS';
export const CLOSE_CART_MODAL = 'CLOSE_CART_MODAL';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const CANCEL_CHECK = 'CANCEL_CHECK';
export const INIT_CANCEL_CHECK = 'INIT_CANCEL_CHECK';
export const CHECKOUT_ORDER = 'CHECKOUT_ORDER';
export const END_CART_OPERATION = 'END_CART_OPERATION';

//Coupon
export const QUERY_COUPON = 'QUERY_COUPON';
export const QUERY_COUPON_SUCCESS = 'QUERY_COUPON_SUCCESS';
export const END_COUPON_CTRL = 'END_COUPON_CTRL';
export const INIT_COUPON = 'INIT_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';

//Wallet
export const QUERY_WALLET = 'QUERY_WALLET';
export const QUERY_WALLET_SUCCESS = 'QUERY_WALLET_SUCCESS';
export const QUERY_JOURNAL = 'QUERY_JOURNAL';
export const QUERY_JOURNAL_SUCCESS = 'QUERY_JOURNAL_SUCCESS';
export const QUERY_JOURNAL_DETAIL = 'QUERY_JOURNAL_DETAIL';
export const QUERY_JOURNAL_DETAIL_SUCCESS = 'QUERY_JOURNAL_DETAIL_SUCCESS';
export const INIT_WALLET = 'INIT_WALLET';
export const WALLET_END = 'WALLET_END';

//Mine
export const GET_USER_MSG = 'GET_USER_MSG';
export const GET_USER_MSG_SUCCESS = 'GET_USER_MSG_SUCCESS';
export const END_USER_MSG_CTRL = 'END_USER_MSG_CTRL';

//EwuCard
export const QUERY_CARD = 'QUERY_CARD';
export const QUERY_CARD_SUCCESS = 'QUERY_CARD_SUCCESS';
export const QUERY_CARD_DETAIL = 'QUERY_CARD_DETAIL';
export const QUERY_CARD_DETAIL_SUCCESS = 'QUERY_CARD_DETAIL_SUCCESS';
export const INIT_CARD = 'INIT_CARD';
export const EWUCARD_END = 'EWUCARD_END';

//Address
export const QUERY_DEFAULT = 'QUERY_DEFAULT';
export const QUERY_DEFAULT_SUCCESS = 'QUERY_DEFAULT_SUCCESS';
export const QUERY_ADDRESS = 'QUERY_ADDRESS';
export const QUERY_ADDRESS_SUCCESS = 'QUERY_ADDRESS_SUCCESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const QUERY_ADDRESS_DETAIL = 'QUERY_ADDRESS_DETAIL';
export const QUERY_ADDRESS_DETAIL_SUCCESS = 'QUERY_ADDRESS_DETAIL_SUCCESS';
export const ADDRESS_END = 'ADDRESS_END';

//PRESUBMIT
export const PRESUBMIT = 'PRESUBMIT';
export const PRESUBMIT_SUCCESS = 'PRESUBMIT_SUCCESS';

//promotion
export const PROMOTION_QUERY = 'PROMTION_QUERY';
export const SUCCESS_PROMOTION_QUERY = 'SUCCESS_PROMOTION_QUERY';
export const PROMOTION_CALCULATE = 'PROMOTION_CALCULATE';
export const SUCCESS_PROMOTION_CALCULATE = 'SUCCESS_PROMOTION_CALCULATE';
export const PROMOTION_END = 'PROMOTION_END';

//Pay
export const CHOOSE_PAYWAY = 'CHOOSE_PAYWAY';
export const GET_PAY_TOKEN = 'GET_PAY_TOKEN';
export const PAY = 'PAY';
export const GET_YIWUCOIN = 'GET_YIWUCOIN';
export const GET_YIWUCOIN_SUCCESS = 'GET_YIWUCOIN_SUCCESS';
export const END_GET_YW = 'END_GET_YW';

//Payresult
export const QUERY_PAY_RESULT = 'QUERY_PAY_RESULT';
export const QUERY_PAY_RESULT_SUCCESS = 'QUERY_PAY_RESULT_SUCCESS';
export const PAY_END = 'PAY_END';

//order
export const QUERY_ORDER_LIST = 'QUERY_ORDER_LIST';
export const QUERY_ORDER_LIST_SUCCESS = 'QUERY_ORDER_LIST_SUCCESS';
export const QUERY_ORDER_DETAIL = 'QUERY_ORDER_DETAIL';
export const QUERY_ORDER_DETAIL_SUCCESS = 'QUERY_ORDER_DETAIL_SUCCESS';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const QUERY_NOWTIME = 'QUERY_NOWTIME';
export const QUERY_NOWTIME_SUCCESS = 'QUERY_NOWTIME_SUCCESS';
export const EXTENDED_ORDER = 'EXTENDED_ORDER';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const CLEAR_ORDER_DETAIL = 'CLEAR_ORDER_DETAIL';
export const ORDER_END = 'ORDER_END';

//refund
export const GET_REFUNDS = 'GET_REFUNDS';
export const GET_REFUNDS_SUCCESS = 'GET_REFUNDS_SUCCESS';
export const GET_REFUND_DETAIL = 'GET_REFUND_DETAIL';
export const GET_REFUND_DETAIL_SUCCESS = 'GET_REFUND_DETAIL_SUCCESS';
export const GET_REFUND_TRACE = 'GET_REFUND_TRACE';
export const GET_REFUND_TRACE_SUCCESS = 'GET_REFUND_TRACE_SUCCESS';
export const END_REFUNDS_CTRL = 'END_REFUNDS_CTRL';

//JDReturned
export const QUERY_JD_RETURN = 'QUERY_JD_RETURN';
export const QUERY_JD_RETURN_SUCCESS = 'QUERY_JD_RETURN_SUCCESS';

//ApplyRefund
export const QUERY_APPLYREFUND = 'QUERY_APPLYREFUND';
export const QUERY_APPLYREFUND_SUCCESS = 'QUERY_APPLYREFUND_SUCCESS';

//RefundInfo
export const QUERY_REFUNDINFO = 'QUERY_REFUNDINFO';
export const QUERY_REFUNDINFO_SUCCESS = 'QUERY_REFUNDINFO_SUCCESS';

//Activity
export const GET_TIMELIMIT_LIST = 'GET_TIMELIMIT_LIST';
export const GET_TIMELIMIT_LIST_SUCCESS = 'GET_TIMELIMIT_LIST_SUCCESS';
export const GET_TIMELIMIT_DETAIL = 'GET_TIMELIMIT_DETAIL';
export const GET_TIMELIMIT_DETAIL_SUCCESS = 'GET_TIMELIMIT_DETAIL_SUCCESS';
export const INIT_ACTIVITY = 'INIT_ACTIVITY';
export const END_ACTIVITY_CTRL = 'END_ACTIVITY_CTRL';

//SubmitOrder
export const GET_PROMOTIONS = 'GET_PROMOTIONS';
export const GET_PROMOTIONS_SUCCESS = 'GET_PROMOTIONS_SUCCESS';
export const CALCULATE_PROMOTIONS = 'CALCULATE_PROMOTIONS';
export const CALCULATE_PROMOTIONS_SUCCESS = 'CACULATE_PROMOTIONS_SUCCESS';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const SUBMITORDER_END = 'SUBMITORDER_END';
export const SET_PAY_URL = 'SET_PAY_URL';
export const INIT_SUBMITORDER = 'INIT_SUBMITORDER';
export const CLOSE_NOTVALID_MODAL = 'CLOSE_NOTVALID_MODAL';

//Express
export const QUERY_EXPRESS = 'QUERY_EXPRESS';
export const QUERY_EXPRESS_SUCCESS = 'QUERY_EXPRESS_SUCCESS';
export const CLEAR_EXPRESS = 'CLEAR_EXPRESS';

//Personal
export const QUERY_PERSONAL = 'QUERY_PERSONAL';
export const QUERY_PERSONAL_SUCCESS = 'QUERY_PERSONAL_SUCCESS';
export const END_PERSONAL_CTRL = 'END_PERSONAL_CTRL';
